//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapImportManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MapImportManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string ChangedTitle {
            get {
                return ResourceManager.GetString("ChangedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved changes will be lost.
        ///Are you really want to exit?.
        /// </summary>
        public static string ConfirmExit {
            get {
                return ResourceManager.GetString("ConfirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved changes will be lost.
        ///Proceed loading?.
        /// </summary>
        public static string ConfirmLoad {
            get {
                return ResourceManager.GetString("ConfirmLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected.
        /// </summary>
        public static string Del {
            get {
                return ResourceManager.GetString("Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeletedTitle {
            get {
                return ResourceManager.GetString("DeletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk path (for new files).
        /// </summary>
        public static string DiskPathTitile {
            get {
                return ResourceManager.GetString("DiskPathTitile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit path.
        /// </summary>
        public static string EditPath {
            get {
                return ResourceManager.GetString("EditPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export all contents.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add some files:.
        /// </summary>
        public static string FailedFiles {
            get {
                return ResourceManager.GetString("FailedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import directory.
        /// </summary>
        public static string ImportDir {
            get {
                return ResourceManager.GetString("ImportDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include parent folder name to path?.
        /// </summary>
        public static string ImportDirVariant {
            get {
                return ResourceManager.GetString("ImportDirVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import files.
        /// </summary>
        public static string ImportFiles {
            get {
                return ResourceManager.GetString("ImportFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warcraft III map or campaign.
        /// </summary>
        public static string Maps {
            get {
                return ResourceManager.GetString("Maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open map or campaign.
        /// </summary>
        public static string OpenMap {
            get {
                return ResourceManager.GetString("OpenMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open map or campaign file.
        ///Ensure it is not opened in World Editor or other applications..
        /// </summary>
        public static string OpenMapError {
            get {
                return ResourceManager.GetString("OpenMapError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string PathTitle {
            get {
                return ResourceManager.GetString("PathTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string SaveMap {
            get {
                return ResourceManager.GetString("SaveMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save map or campaign file.
        ///Ensure it is not opened in World Editor or other applications..
        /// </summary>
        public static string SaveMapError {
            get {
                return ResourceManager.GetString("SaveMapError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t load StomLib..
        /// </summary>
        public static string StormLibError {
            get {
                return ResourceManager.GetString("StormLibError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
